version: 2

registries:
  fortawesome:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: ${{ secrets.FONTAWESOME_TOKEN }}

updates:
  - package-ecosystem: npm
    registries:
      - fortawesome
    directory: /
    schedule:
      interval: daily
      time: '05:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 30
