name: Delivery to preview

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for dispatching it manually.
        type: string
        default: manual healthcheck
        required: true

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/cd.preview.yml'
      - 'public/**/*'
      - 'stories/**/*'
      - '.npmrc'
      - '**.css'
      - '**.jsx?'
      - '**.tsx?'
      - '*.json'
      - '!tools/**/*'

  schedule:
    - cron: 0 7 1 * * # at 07:00 on day-of-month 1, UTC

jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest
    if: ! contains(fromJSON('["dependabot[bot]", "renovate[bot]"]'), github.actor)
    environment:
      name: chromatic
      url: ${{ steps.deployment.outputs.storybookUrl }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
          check-latest: true
      - name: Install dependencies
        run: npm ci
        env: { FONTAWESOME_TOKEN: '${{ secrets.FONTAWESOME_TOKEN }}' }

      - name: Publish to Chromatic
        id: deployment
        uses: chromaui/action@v1
        with:
          buildScriptName: build
          debug: false
          diagnostics: false
          dryRun: false
          exitZeroOnChanges: true
          exitOnceUploaded: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  notify:
    name: Notifying
    needs: [ publish ]
    runs-on: ubuntu-latest
    if: failure() || success()

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Send notification
        uses: ./.github/actions/notify
        continue-on-error: true
        with:
          emoji: 🎁
          channel: ${{ secrets.SLACK_WEBHOOK }}
          success: ${{ ! contains(needs.*.result, 'failure') }}
